//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace IrbAnalyser.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MED_PROD_903Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MED_PROD_903Entities object using the connection string found in the 'MED_PROD_903Entities' section of the application configuration file.
        /// </summary>
        public MED_PROD_903Entities() : base("name=MED_PROD_903Entities", "MED_PROD_903Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MED_PROD_903Entities object.
        /// </summary>
        public MED_PROD_903Entities(string connectionString) : base(connectionString, "MED_PROD_903Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MED_PROD_903Entities object.
        /// </summary>
        public MED_PROD_903Entities(EntityConnection connection) : base(connection, "MED_PROD_903Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<A_GEN_STUDY_INITIAL_REVIEW> A_GEN_STUDY_INITIAL_REVIEW
        {
            get
            {
                if ((_A_GEN_STUDY_INITIAL_REVIEW == null))
                {
                    _A_GEN_STUDY_INITIAL_REVIEW = base.CreateObjectSet<A_GEN_STUDY_INITIAL_REVIEW>("A_GEN_STUDY_INITIAL_REVIEW");
                }
                return _A_GEN_STUDY_INITIAL_REVIEW;
            }
        }
        private ObjectSet<A_GEN_STUDY_INITIAL_REVIEW> _A_GEN_STUDY_INITIAL_REVIEW;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the A_GEN_STUDY_INITIAL_REVIEW EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToA_GEN_STUDY_INITIAL_REVIEW(A_GEN_STUDY_INITIAL_REVIEW a_GEN_STUDY_INITIAL_REVIEW)
        {
            base.AddObject("A_GEN_STUDY_INITIAL_REVIEW", a_GEN_STUDY_INITIAL_REVIEW);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MED_PROD_903Model", Name="A_GEN_STUDY_INITIAL_REVIEW")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class A_GEN_STUDY_INITIAL_REVIEW : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new A_GEN_STUDY_INITIAL_REVIEW object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="x_PK_INDEX">Initial value of the X_PK_INDEX property.</param>
        /// <param name="x_ACTION">Initial value of the X_ACTION property.</param>
        /// <param name="x_ID_MODIFIED">Initial value of the X_ID_MODIFIED property.</param>
        /// <param name="x_DATE_MODIFIED">Initial value of the X_DATE_MODIFIED property.</param>
        public static A_GEN_STUDY_INITIAL_REVIEW CreateA_GEN_STUDY_INITIAL_REVIEW(global::System.Int32 id, global::System.Int32 x_PK_INDEX, global::System.String x_ACTION, global::System.Int32 x_ID_MODIFIED, global::System.DateTime x_DATE_MODIFIED)
        {
            A_GEN_STUDY_INITIAL_REVIEW a_GEN_STUDY_INITIAL_REVIEW = new A_GEN_STUDY_INITIAL_REVIEW();
            a_GEN_STUDY_INITIAL_REVIEW.ID = id;
            a_GEN_STUDY_INITIAL_REVIEW.X_PK_INDEX = x_PK_INDEX;
            a_GEN_STUDY_INITIAL_REVIEW.X_ACTION = x_ACTION;
            a_GEN_STUDY_INITIAL_REVIEW.X_ID_MODIFIED = x_ID_MODIFIED;
            a_GEN_STUDY_INITIAL_REVIEW.X_DATE_MODIFIED = x_DATE_MODIFIED;
            return a_GEN_STUDY_INITIAL_REVIEW;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 X_PK_INDEX
        {
            get
            {
                return _X_PK_INDEX;
            }
            set
            {
                if (_X_PK_INDEX != value)
                {
                    OnX_PK_INDEXChanging(value);
                    ReportPropertyChanging("X_PK_INDEX");
                    _X_PK_INDEX = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("X_PK_INDEX");
                    OnX_PK_INDEXChanged();
                }
            }
        }
        private global::System.Int32 _X_PK_INDEX;
        partial void OnX_PK_INDEXChanging(global::System.Int32 value);
        partial void OnX_PK_INDEXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String X_ACTION
        {
            get
            {
                return _X_ACTION;
            }
            set
            {
                OnX_ACTIONChanging(value);
                ReportPropertyChanging("X_ACTION");
                _X_ACTION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("X_ACTION");
                OnX_ACTIONChanged();
            }
        }
        private global::System.String _X_ACTION;
        partial void OnX_ACTIONChanging(global::System.String value);
        partial void OnX_ACTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 X_ID_MODIFIED
        {
            get
            {
                return _X_ID_MODIFIED;
            }
            set
            {
                OnX_ID_MODIFIEDChanging(value);
                ReportPropertyChanging("X_ID_MODIFIED");
                _X_ID_MODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("X_ID_MODIFIED");
                OnX_ID_MODIFIEDChanged();
            }
        }
        private global::System.Int32 _X_ID_MODIFIED;
        partial void OnX_ID_MODIFIEDChanging(global::System.Int32 value);
        partial void OnX_ID_MODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime X_DATE_MODIFIED
        {
            get
            {
                return _X_DATE_MODIFIED;
            }
            set
            {
                OnX_DATE_MODIFIEDChanging(value);
                ReportPropertyChanging("X_DATE_MODIFIED");
                _X_DATE_MODIFIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("X_DATE_MODIFIED");
                OnX_DATE_MODIFIEDChanged();
            }
        }
        private global::System.DateTime _X_DATE_MODIFIED;
        partial void OnX_DATE_MODIFIEDChanging(global::System.DateTime value);
        partial void OnX_DATE_MODIFIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE_TODAY
        {
            get
            {
                return _DATE_TODAY;
            }
            set
            {
                OnDATE_TODAYChanging(value);
                ReportPropertyChanging("DATE_TODAY");
                _DATE_TODAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_TODAY");
                OnDATE_TODAYChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE_TODAY;
        partial void OnDATE_TODAYChanging(Nullable<global::System.DateTime> value);
        partial void OnDATE_TODAYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SYS_STUDY_TITLE
        {
            get
            {
                return _SYS_STUDY_TITLE;
            }
            set
            {
                OnSYS_STUDY_TITLEChanging(value);
                ReportPropertyChanging("SYS_STUDY_TITLE");
                _SYS_STUDY_TITLE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SYS_STUDY_TITLE");
                OnSYS_STUDY_TITLEChanged();
            }
        }
        private global::System.String _SYS_STUDY_TITLE;
        partial void OnSYS_STUDY_TITLEChanging(global::System.String value);
        partial void OnSYS_STUDY_TITLEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INIT_STUDY_NUMBER
        {
            get
            {
                return _INIT_STUDY_NUMBER;
            }
            set
            {
                OnINIT_STUDY_NUMBERChanging(value);
                ReportPropertyChanging("INIT_STUDY_NUMBER");
                _INIT_STUDY_NUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("INIT_STUDY_NUMBER");
                OnINIT_STUDY_NUMBERChanged();
            }
        }
        private global::System.String _INIT_STUDY_NUMBER;
        partial void OnINIT_STUDY_NUMBERChanging(global::System.String value);
        partial void OnINIT_STUDY_NUMBERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SYS_PRINCIPAL_INVESTIGATOR
        {
            get
            {
                return _SYS_PRINCIPAL_INVESTIGATOR;
            }
            set
            {
                OnSYS_PRINCIPAL_INVESTIGATORChanging(value);
                ReportPropertyChanging("SYS_PRINCIPAL_INVESTIGATOR");
                _SYS_PRINCIPAL_INVESTIGATOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SYS_PRINCIPAL_INVESTIGATOR");
                OnSYS_PRINCIPAL_INVESTIGATORChanged();
            }
        }
        private global::System.String _SYS_PRINCIPAL_INVESTIGATOR;
        partial void OnSYS_PRINCIPAL_INVESTIGATORChanging(global::System.String value);
        partial void OnSYS_PRINCIPAL_INVESTIGATORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LAY_SUMMARY
        {
            get
            {
                return _LAY_SUMMARY;
            }
            set
            {
                OnLAY_SUMMARYChanging(value);
                ReportPropertyChanging("LAY_SUMMARY");
                _LAY_SUMMARY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LAY_SUMMARY");
                OnLAY_SUMMARYChanged();
            }
        }
        private global::System.String _LAY_SUMMARY;
        partial void OnLAY_SUMMARYChanging(global::System.String value);
        partial void OnLAY_SUMMARYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ONGOING_SUBMISSION_SCREEN
        {
            get
            {
                return _ONGOING_SUBMISSION_SCREEN;
            }
            set
            {
                OnONGOING_SUBMISSION_SCREENChanging(value);
                ReportPropertyChanging("ONGOING_SUBMISSION_SCREEN");
                _ONGOING_SUBMISSION_SCREEN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ONGOING_SUBMISSION_SCREEN");
                OnONGOING_SUBMISSION_SCREENChanged();
            }
        }
        private global::System.String _ONGOING_SUBMISSION_SCREEN;
        partial void OnONGOING_SUBMISSION_SCREENChanging(global::System.String value);
        partial void OnONGOING_SUBMISSION_SCREENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SIGNATURE_UNDERSTAND
        {
            get
            {
                return _SIGNATURE_UNDERSTAND;
            }
            set
            {
                OnSIGNATURE_UNDERSTANDChanging(value);
                ReportPropertyChanging("SIGNATURE_UNDERSTAND");
                _SIGNATURE_UNDERSTAND = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SIGNATURE_UNDERSTAND");
                OnSIGNATURE_UNDERSTANDChanged();
            }
        }
        private global::System.String _SIGNATURE_UNDERSTAND;
        partial void OnSIGNATURE_UNDERSTANDChanging(global::System.String value);
        partial void OnSIGNATURE_UNDERSTANDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SUBMISSION_REFERENCE_NUMBER
        {
            get
            {
                return _SUBMISSION_REFERENCE_NUMBER;
            }
            set
            {
                OnSUBMISSION_REFERENCE_NUMBERChanging(value);
                ReportPropertyChanging("SUBMISSION_REFERENCE_NUMBER");
                _SUBMISSION_REFERENCE_NUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SUBMISSION_REFERENCE_NUMBER");
                OnSUBMISSION_REFERENCE_NUMBERChanged();
            }
        }
        private global::System.String _SUBMISSION_REFERENCE_NUMBER;
        partial void OnSUBMISSION_REFERENCE_NUMBERChanging(global::System.String value);
        partial void OnSUBMISSION_REFERENCE_NUMBERChanged();

        #endregion

    
    }

    #endregion

    
}
