//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrbAnalyser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ER_CODELST
    {
        public decimal PK_CODELST { get; set; }
        public Nullable<decimal> FK_ACCOUNT { get; set; }
        public string CODELST_TYPE { get; set; }
        public string CODELST_SUBTYP { get; set; }
        public string CODELST_DESC { get; set; }
        public string CODELST_HIDE { get; set; }
        public Nullable<decimal> CODELST_SEQ { get; set; }
        public string CODELST_MAINT { get; set; }
        public Nullable<decimal> RID { get; set; }
        public Nullable<decimal> CREATOR { get; set; }
        public Nullable<decimal> LAST_MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string IP_ADD { get; set; }
        public string CODELST_CUSTOM_COL { get; set; }
        public string CODELST_CUSTOM_COL1 { get; set; }
        public string CODELST_STUDY_ROLE { get; set; }
        public string CODELST_KIND { get; set; }
    }
}
