//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrbAnalyser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ER_STUDYAPNDX
    {
        public decimal PK_STUDYAPNDX { get; set; }
        public Nullable<decimal> FK_STUDY { get; set; }
        public string STUDYAPNDX_TYPE { get; set; }
        public string STUDYAPNDX_URI { get; set; }
        public string STUDYAPNDX_DESC { get; set; }
        public string STUDYAPNDX_PUBFLAG { get; set; }
        public Nullable<decimal> RID { get; set; }
        public Nullable<decimal> CREATOR { get; set; }
        public Nullable<decimal> LAST_MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string STUDYAPNDX_FILE { get; set; }
        public byte[] STUDYAPNDX_FILEOBJ { get; set; }
        public string IP_ADD { get; set; }
        public Nullable<int> STUDYAPNDX_FILESIZE { get; set; }
        public Nullable<decimal> FK_STUDYVER { get; set; }
    
        public virtual ER_STUDYVER ER_STUDYVER { get; set; }
    }
}
