//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrbAnalyser.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VelosStg : DbContext
    {
        public VelosStg()
            : base("name=VelosStg")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ER_CODELST> ER_CODELST { get; set; }
        public DbSet<ER_STUDYAPNDX> ER_STUDYAPNDX { get; set; }
        public DbSet<ER_STUDYVER> ER_STUDYVER { get; set; }
        public DbSet<VDA_V_ER_CODELST> VDA_V_ER_CODELST { get; set; }
        public DbSet<VDA_V_STUDY_SUMMARY> VDA_V_STUDY_SUMMARY { get; set; }
        public DbSet<VDA_V_STUDYSITES> VDA_V_STUDYSITES { get; set; }
        public DbSet<VDA_V_STUDYSTAT> VDA_V_STUDYSTAT { get; set; }
        public DbSet<VDA_V_STUDYTEAM_MEMBERS> VDA_V_STUDYTEAM_MEMBERS { get; set; }
    }
}
