//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrbAnalyser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDA_V_STUDY_SUMMARY
    {
        public decimal PK_STUDY { get; set; }
        public string STUDY_NUMBER { get; set; }
        public string STUDY_ENTERED_BY { get; set; }
        public string STUDY_PI { get; set; }
        public string STUDY_COORDINATOR { get; set; }
        public string STUDY_MAJ_AUTH { get; set; }
        public string STUDY_TITLE { get; set; }
        public string STUDY_OBJECTIVE { get; set; }
        public string STUDY_SUMMARY { get; set; }
        public string STUDY_AGENT_DEVICE { get; set; }
        public string STUDY_DIVISION { get; set; }
        public string STUDY_TAREA { get; set; }
        public string STUDY_DISEASE_SITE { get; set; }
        public string STUDY_ICDCODE1 { get; set; }
        public string STUDY_ICDCODE2 { get; set; }
        public Nullable<decimal> STUDY_NATSAMPSIZE { get; set; }
        public Nullable<short> STUDY_DURATION { get; set; }
        public string STUDY_DURATN_UNIT { get; set; }
        public Nullable<System.DateTime> STUDY_EST_BEGIN_DATE { get; set; }
        public string STUDY_PHASE { get; set; }
        public string STUDY_RESEARCH_TYPE { get; set; }
        public string STUDY_TYPE { get; set; }
        public string STUDY_LINKED_TO { get; set; }
        public string STUDY_BLINDING { get; set; }
        public string STUDY_RANDOM { get; set; }
        public string STUDY_SPONSOR { get; set; }
        public string SPONSOR_CONTACT { get; set; }
        public string STUDY_INFO { get; set; }
        public string STUDY_KEYWRDS { get; set; }
        public Nullable<decimal> FK_ACCOUNT { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public string CREATOR { get; set; }
        public string SPONSOR_DD { get; set; }
        public string STUDY_SPONSORID { get; set; }
        public Nullable<System.DateTime> STUDY_ACTUALDT { get; set; }
        public string STUDY_INVIND_FLAG { get; set; }
        public Nullable<System.DateTime> CTRP_ACCRREP_LASTRUN_DATE { get; set; }
        public Nullable<System.DateTime> CTRP_ACCRUAL_GEN_DATE { get; set; }
        public Nullable<System.DateTime> CTRP_CUTOFF_DATE { get; set; }
        public string CTRP_LAST_DOWNLOAD_BY { get; set; }
        public string NCI_TRIAL_IDENTIFIER { get; set; }
        public string NCT_NUMBER { get; set; }
        public Nullable<decimal> STUDY_ENTERED_BY_FK { get; set; }
        public string STUDY_PI_FK { get; set; }
        public Nullable<decimal> STUDY_COORDINATOR_FK { get; set; }
        public Nullable<decimal> STUDY_DIVISION_FK { get; set; }
        public Nullable<decimal> STUDY_TAREA_FK { get; set; }
        public string STUDY_DISEASE_SITE_FK { get; set; }
        public Nullable<decimal> STUDY_PHASE_FK { get; set; }
        public Nullable<decimal> STUDY_RESEARCH_TYPE_FK { get; set; }
        public Nullable<decimal> STUDY_TYPE_FK { get; set; }
        public Nullable<decimal> STUDY_BLINDING_FK { get; set; }
        public Nullable<decimal> STUDY_RANDOM_FK { get; set; }
        public Nullable<decimal> CREATOR_FK { get; set; }
        public Nullable<decimal> LAST_MODIFIED_BY_FK { get; set; }
        public Nullable<decimal> SPONSOR_DD_FK { get; set; }
        public Nullable<decimal> CTRP_LAST_DOWNLOAD_BY_FK { get; set; }
        public string STUDY_SCOPE { get; set; }
    }
}
