//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrbAnalyser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDA_V_ER_CODELST
    {
        public decimal PK_CODELST { get; set; }
        public string CODELST_TYPE { get; set; }
        public string CODELST_SUBTYP { get; set; }
        public string CODELST_DESC { get; set; }
        public string CODELST_HIDE { get; set; }
        public Nullable<decimal> CODELST_SEQ { get; set; }
        public string CODELST_CUSTOM_COL { get; set; }
        public string CODELST_CUSTOM_COL1 { get; set; }
        public string CODELST_STUDY_ROLE { get; set; }
    }
}
