//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrbAnalyser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDA_V_STUDYTEAM_MEMBERS
    {
        public string STUDY_NUMBER { get; set; }
        public string STUDY_TITLE { get; set; }
        public string USER_SITE_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PHONE { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_ADDRESS { get; set; }
        public string ROLE { get; set; }
        public Nullable<decimal> FK_STUDY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<decimal> FK_ACCOUNT { get; set; }
        public string CREATOR { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public Nullable<decimal> RID { get; set; }
        public decimal PK_STUDYTEAM { get; set; }
        public string STUDYTEAM_STATUS { get; set; }
        public Nullable<decimal> LAST_MODIFIED_BY_FK { get; set; }
        public Nullable<decimal> CREATOR_FK { get; set; }
    }
}
