//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrbAnalyser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDA_V_STUDYSTAT
    {
        public string STUDY_NUMBER { get; set; }
        public Nullable<System.DateTime> STUDY_START_DATE { get; set; }
        public Nullable<System.DateTime> STUDY_END_DATE { get; set; }
        public string SSTAT_SITE_NAME { get; set; }
        public string SSTAT_STUDY_STATUS { get; set; }
        public Nullable<System.DateTime> SSTAT_VALID_FROM { get; set; }
        public Nullable<System.DateTime> SSTAT_VALID_UNTIL { get; set; }
        public string SSTAT_NOTES { get; set; }
        public string SSTAT_DOCUMNTD_BY { get; set; }
        public Nullable<System.DateTime> SSTAT_END_DATE_SYSTEM { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE { get; set; }
        public decimal PK_STUDYSTAT { get; set; }
        public Nullable<decimal> FK_STUDY { get; set; }
        public Nullable<decimal> SSTAT_FK_SITE { get; set; }
        public Nullable<decimal> FK_ACCOUNT { get; set; }
        public string SSTAT_CURRENT_STAT { get; set; }
        public Nullable<decimal> SSTAT_STATUS_TYPE_FK { get; set; }
        public string SSTAT_STATUS_TYPE { get; set; }
        public Nullable<decimal> LAST_MODIFIED_BY_FK { get; set; }
        public Nullable<decimal> CREATOR_FK { get; set; }
    }
}
