//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IrbAnalyser.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDA_V_STUDYSITES
    {
        public decimal PK_STUDYSITES { get; set; }
        public Nullable<decimal> FK_STUDY { get; set; }
        public Nullable<decimal> FK_SITE { get; set; }
        public string STUDYSITE_TYPE { get; set; }
        public string STUDYSITE_LSAMPLESIZE { get; set; }
        public string IS_STUDYSITE_PUBLIC { get; set; }
        public string INCLUDE_IN_REPORTS { get; set; }
        public Nullable<decimal> RID { get; set; }
        public string CREATOR { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_ON { get; set; }
        public string IP_ADD { get; set; }
        public Nullable<decimal> STUDYSITE_ENRCOUNT { get; set; }
        public string IS_REVIEWBASED_ENR { get; set; }
        public string SEND_ENROLLMENT_NOTIFICATION { get; set; }
        public string SEND_ENROLLMENT_APPROVAL { get; set; }
        public string STUDY_NUMBER { get; set; }
        public string SITE_NAME { get; set; }
        public Nullable<decimal> FK_ACCOUNT { get; set; }
        public Nullable<decimal> LAST_MODIFIED_BY_FK { get; set; }
        public Nullable<decimal> CREATOR_FK { get; set; }
    }
}
